#!/usr/bin/env python
from setuptools import setup, find_packages

setup(name='NMTGMinor',
      version='0.1',
      author='quanpn90',
      author_email='ngoc.pham@kit.edu',
      url='https://github.com/quanpn90/NMTGMinor',
      license='MIT',
      scripts=[
          'autoencoder.py',
          'average_checkpoints_auto.py',
          'classify.py',
          'eval_autoencoder.py',
          'extend_weight.py',
          'extract_wav2vec2_codebook.py',
          'extract_wav2vec2_tdnn.py',
          'flask_online.py',
          'online.py',
          'preprocess_classify.py',
          'preprocess.py',
          'rematch_language_embedding.py',
          'rescore.py',
          'sample_lm.py',
          'train_classify.py',
          'train_distributed.py',
          'train_language_model.py',
          'train.py',
          'translate_distributed.py',
          'translate.py',
          'verify_wav2vec2_feat.py',
      ],
      packages=find_packages(),
      install_requires=['torch', 'apex', 'h5py', 'torchaudio', 'soundfile'])
